# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Build and deploy'

on:
  schedule:
    # Run hourly at xx:05.
    - cron: '05 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Update last known good versions per channel
        run: |
          git config user.name 'Chrome for Testing bot'
          git config user.email 'mathias+cft@chromium.org'
          git add data
          git commit data -m 'Update latest available version numbers' || true
          git push

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@a1ea191d508feb8485aceba848389d49f80ca2dc # v4.4.3
        with:
          branch: gh-pages
          folder: dist
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          single-commit: true
          git-config-name: Chrome for Testing bot
          git-config-email: mathias+cft@chromium.org
